<script setup lang="ts">

const { locale } = useI18n()

const data = {
  en: {
    hero: {
      "size": "max",
      "ab_testing": null,
      "uppercase": false,
      "transitiontime": null,
      "overlay": "partial",
      "soundonscroll": false,
      "cards": [
        {
          "id": 128,
          "title": "PREMIER ELEGANCE ACROSS THE GLOBE ",
          "description": null,
          "timerText": null,
          "timerDateTime": null,
          "startDate": null,
          "endDate": null,
          "btnExternal": null,
          "timecard": null,
          "idcard": null,
          "media": {
            "id": 728,
            "name": "index.png",
            "url": "assets/img/heroes/index.png",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/png",
            "isUrlSigned": false
          },
          "mediam": null,
          "btninternal": null,
          "btnmodal": null
        }
      ],
      "countries": null
    },
    carouselBadges: {
      "title": "We Are PR Global",
      "description": "A full-service tour operator redefining how the world travels.",
      "decorativeLine": true,
      "htag": "h1",
      "btnText": "Learn More",
      "cards": [
        {
          "id": 3,
          "urlexternal": "https://www.moonpalace.com",
          "media": {
            "id": 599,
            "name": "Moon Palace.png",
            "url": "assets/img/caousel-badges/Moon_Palace_ff32ef74b8.png",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/png",
            "isUrlSigned": false
          }
        },
        {
          "id": 4,
          "urlexternal": "https://www.palaceresorts.com",
          "media": {
            "id": 594,
            "name": "Palace_Resorts_Blue.png",
            "url": "assets/img/caousel-badges/Palace_Resorts_Blue_605ef2b293.png",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/png",
            "isUrlSigned": false
          }
        },
        {
          "id": 13,
          "urlexternal": "https://www.leblancsparesorts.com",
          "media": {
            "id": 798,
            "name": "lbb_hotels_resorts_black_footer.svg",
            "url": "assets/img/caousel-badges/lbb_hotels_resorts_black_footer_bb4d70a02d.svg",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/svg+xml",
            "isUrlSigned": false
          }
        },
        {
          "id": 14,
          "urlexternal": "https://www.baglionihotels.com",
          "media": {
            "id": 741,
            "name": "baglioni-logo.svg",
            "url": "assets/img/caousel-badges/baglioni_logo_94c83cc23e.svg",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/svg+xml",
            "isUrlSigned": false
          }
        },
        {
          "id": 5,
          "urlexternal": "https://www.palaceelite.com",
          "media": {
            "id": 738,
            "name": "palace-elite.svg",
            "url": "assets/img/caousel-badges/palace_elite_05e7c6f3c6.svg",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/svg+xml",
            "isUrlSigned": false
          }
        }
      ],
      "countries": null
    },
    contentGroup: {
      "stylecomponent": "Colum",
      "component": "ContentGroup",
      "enablebg": false,
      "countries": null,
      "cards": [
        {
          "id": 128,
          "title": "Itinerary creation",
          "tag": null,
          "description": "We design complete travel experiences that integrate flights, accommodation, local transfers, tours, entertainment, and cultural immersion.",
          "disclaimer": null,
          "bookto": null,
          "bookfrom": null,
          "textbook": null,
          "bookstart": null,
          "stayto": null,
          "stayfrom": null,
          "textstay": null,
          "staystart": null,
          "btnltext": null,
          "btnlexternal": null,
          "btnrtext": null,
          "btnrexternal": null,
          "decorativeline": true,
          "playvideo": true,
          "startdate": null,
          "enddate": null,
          "textbookto": null,
          "textstayto": null,
          "enableicon": false,
          "align": "left",
          "media": {
            "id": 2394,
            "name": "los-cabos-travel-destination-le-blanc-spa-resorts.webp",
            "alternativeText": null,
            "caption": null,
            "width": 768,
            "height": 650,
            "imageformats": null,
            "hash": "los_cabos_travel_destination_le_blanc_spa_resorts_c54af9ab23",
            "ext": ".webp",
            "mime": "image/webp",
            "size": 41.91,
            "url": "https://www.leblancsparesorts.com/los_cabos_travel_destination_le_blanc_spa_resorts_c54af9ab23.webp",
            "previewUrl": null,
            "provider": "aws-s3",
            "provider_metadata": null,
            "isUrlSigned": true
          },
          "btnrinternal": null,
          "btnrmodal": null,
          "btnlinternal": null,
          "btnlmodal": null
        },
        {
          "id": 129,
          "title": "Direct Negotiations",
          "tag": null,
          "description": "We partner with top-tier hotels, airlines, restaurants, and experience providers to offer exclusive pricing and access you won’t find on consumer platforms.",
          "disclaimer": null,
          "bookto": null,
          "bookfrom": null,
          "textbook": null,
          "bookstart": null,
          "stayto": null,
          "stayfrom": null,
          "textstay": null,
          "staystart": null,
          "btnltext": null,
          "btnlexternal": null,
          "btnrtext": null,
          "btnrexternal": null,
          "decorativeline": true,
          "playvideo": true,
          "startdate": null,
          "enddate": null,
          "textbookto": null,
          "textstayto": null,
          "enableicon": false,
          "align": "left",
          "media": {
            "id": 1955,
            "name": "ancestral-massage-spa-le-blanc-spa-resorts.webp",
            "alternativeText": "Healing touch Spa",
            "caption": "Achieve a complete state of wellbeing",
            "width": 1620,
            "height": 1080,
            "imageformats": null,
            "hash": "ancestral-massage-spa-le-blanc-spa-resorts_cd9c0112ba",
            "ext": ".webp",
            "mime": "image/webp",
            "size": 105.74,
            "url": "https://www.leblancsparesorts.com/ancestral-massage-spa-le-blanc-spa-resorts_cd9c0112ba.webp",
            "previewUrl": null,
            "provider": "aws-s3",
            "provider_metadata": null,
            "isUrlSigned": true
          },
          "btnrinternal": null,
          "btnrmodal": null,
          "btnlinternal": null,
          "btnlmodal": null
        },
        {
          "id": 130,
          "title": "End-to-end coordination",
          "tag": null,
          "description": "We handle every detail — so our travelers can focus on enjoying, not planning.",
          "disclaimer": null,
          "bookto": null,
          "bookfrom": null,
          "textbook": null,
          "bookstart": null,
          "stayto": null,
          "stayfrom": null,
          "textstay": null,
          "staystart": null,
          "btnltext": null,
          "btnlexternal": null,
          "btnrtext": null,
          "btnrexternal": null,
          "decorativeline": true,
          "playvideo": true,
          "startdate": null,
          "enddate": null,
          "textbookto": null,
          "textstayto": null,
          "enableicon": false,
          "align": "left",
          "media": {
            "id": 2394,
            "name": "los-cabos-travel-destination-le-blanc-spa-resorts.webp",
            "alternativeText": null,
            "caption": null,
            "width": 768,
            "height": 650,
            "imageformats": null,
            "hash": "los_cabos_travel_destination_le_blanc_spa_resorts_c54af9ab23",
            "ext": ".webp",
            "mime": "image/webp",
            "size": 41.91,
            "url": "https://www.leblancsparesorts.com/los_cabos_travel_destination_le_blanc_spa_resorts_c54af9ab23.webp",
            "previewUrl": null,
            "provider": "aws-s3",
            "provider_metadata": null,
            "isUrlSigned": true
          },
          "btnrinternal": null,
          "btnrmodal": null,
          "btnlinternal": null,
          "btnlmodal": null
        }
      ]
    },
    contentGroup2: {
      "stylecomponent": "Colum",
      "component": "ContentGroup",
      "enablebg": false,
      "countries": null,
      "cards": [
        {
          "id": 128,
          "title": "On-trip support",
          "tag": null,
          "description": "Our guests have on-the-ground assistance before, during, and after their trip — peace of mind guaranteed.",
          "disclaimer": null,
          "bookto": null,
          "bookfrom": null,
          "textbook": null,
          "bookstart": null,
          "stayto": null,
          "stayfrom": null,
          "textstay": null,
          "staystart": null,
          "btnltext": null,
          "btnlexternal": null,
          "btnrtext": null,
          "btnrexternal": null,
          "decorativeline": true,
          "playvideo": true,
          "startdate": null,
          "enddate": null,
          "textbookto": null,
          "textstayto": null,
          "enableicon": false,
          "align": "left",
          "media": {
            "id": 2394,
            "name": "los-cabos-travel-destination-le-blanc-spa-resorts.webp",
            "alternativeText": null,
            "caption": null,
            "width": 768,
            "height": 650,
            "imageformats": null,
            "hash": "los_cabos_travel_destination_le_blanc_spa_resorts_c54af9ab23",
            "ext": ".webp",
            "mime": "image/webp",
            "size": 41.91,
            "url": "https://www.leblancsparesorts.com/los_cabos_travel_destination_le_blanc_spa_resorts_c54af9ab23.webp",
            "previewUrl": null,
            "provider": "aws-s3",
            "provider_metadata": null,
            "isUrlSigned": true
          },
          "btnrinternal": null,
          "btnrmodal": null,
          "btnlinternal": null,
          "btnlmodal": null
        },
        {
          "id": 129,
          "title": "Flexible to your budget",
          "tag": null,
          "description": "From ultra-luxury to value-based packages, we scale experiences to fit your needs — without sacrificing service quality.",
          "disclaimer": null,
          "bookto": null,
          "bookfrom": null,
          "textbook": null,
          "bookstart": null,
          "stayto": null,
          "stayfrom": null,
          "textstay": null,
          "staystart": null,
          "btnltext": null,
          "btnlexternal": null,
          "btnrtext": null,
          "btnrexternal": null,
          "decorativeline": true,
          "playvideo": true,
          "startdate": null,
          "enddate": null,
          "textbookto": null,
          "textstayto": null,
          "enableicon": false,
          "align": "left",
          "media": {
            "id": 1955,
            "name": "ancestral-massage-spa-le-blanc-spa-resorts.webp",
            "alternativeText": "Healing touch Spa",
            "caption": "Achieve a complete state of wellbeing",
            "width": 1620,
            "height": 1080,
            "imageformats": null,
            "hash": "ancestral-massage-spa-le-blanc-spa-resorts_cd9c0112ba",
            "ext": ".webp",
            "mime": "image/webp",
            "size": 105.74,
            "url": "https://www.leblancsparesorts.com/ancestral-massage-spa-le-blanc-spa-resorts_cd9c0112ba.webp",
            "previewUrl": null,
            "provider": "aws-s3",
            "provider_metadata": null,
            "isUrlSigned": true
          },
          "btnrinternal": null,
          "btnrmodal": null,
          "btnlinternal": null,
          "btnlmodal": null
        },
        {
          "id": 130,
          "title": "Global market intelligence",
          "tag": null,
          "description": "We continually research travel trends and destination demand to build packages aligned with traveler desires and high-value markets.",
          "disclaimer": null,
          "bookto": null,
          "bookfrom": null,
          "textbook": null,
          "bookstart": null,
          "stayto": null,
          "stayfrom": null,
          "textstay": null,
          "staystart": null,
          "btnltext": null,
          "btnlexternal": null,
          "btnrtext": null,
          "btnrexternal": null,
          "decorativeline": true,
          "playvideo": true,
          "startdate": null,
          "enddate": null,
          "textbookto": null,
          "textstayto": null,
          "enableicon": false,
          "align": "left",
          "media": {
            "id": 2394,
            "name": "los-cabos-travel-destination-le-blanc-spa-resorts.webp",
            "alternativeText": null,
            "caption": null,
            "width": 768,
            "height": 650,
            "imageformats": null,
            "hash": "los_cabos_travel_destination_le_blanc_spa_resorts_c54af9ab23",
            "ext": ".webp",
            "mime": "image/webp",
            "size": 41.91,
            "url": "https://www.leblancsparesorts.com/los_cabos_travel_destination_le_blanc_spa_resorts_c54af9ab23.webp",
            "previewUrl": null,
            "provider": "aws-s3",
            "provider_metadata": null,
            "isUrlSigned": true
          },
          "btnrinternal": null,
          "btnrmodal": null,
          "btnlinternal": null,
          "btnlmodal": null
        }
      ]
    },
    contentAlign: {
      "layout": "align",
      "title": "Fully Personalized Travel Experiences",
      "description": "Powered by strategic alliances with world-class hotel operators, we offer more than just bookings — we orchestrate complete journeys, including:",
      "list": "Flights\nTransfers\nAccommodations\nActivities\nCar Rental",
      "align": "left",
      "tag": null,
      "iconlist": "bullet",
      "viewmore": "Ver mas",
      "viewless": "Ver menos",
      "stayfrom": null,
      "stayto": null,
      "btnltext": '',
      "btnlexternal": null,
      "btnrtext": '',
      "btnrexternal": null,
      "startdate": null,
      "enddate": null,
      "bookfrom": null,
      "bookto": null,
      "decorativeline": true,
      "textbook": null,
      "bookstart": null,
      "textstay": null,
      "staystart": null,
      "disclaimer": null,
      "ab_testing": null,
      "largedescription": null,
      "showmodal": null,
      "titlemodal": null,
      "disableviewmore": false,
      "textbookto": null,
      "textstayto": null,
      "countries": null,
      "media": {
        "id": 580,
        "name": "environment-palace-foundation-the-palace-company.webp",
        "url": "assets/img/content-align/environment-palace-foundation-the-palace-company.webp",
        "caption": null,
        "alternativeText": null,
        "imageformats": null,
        "mime": "image/webp",
        "isUrlSigned": false
      },
      "btnlinternal": null,
      "btnrinternal": null,
      "btnlmodal": null,
      "btnrmodal": null
    },
    contentIntro: {
      "title": "What We Do",
      "description": "We create journeys. Not transactions.\n\nAs a tour operator, PR Global goes beyond reservations to build immersive, end-to-end travel packages with unmatched coordination and personalization.",
      "decorativeLine": true,
      "tagH": "h2",
      "btnltext": null,
      "btnlexternal": null,
      "btnrtext": null,
      "btnrexternal": null,
      "removepaddingbottom": false,
      "ab_testing": null,
      "timerdatetime": null,
      "timertext": null,
      "themetimer": "default",
      "sizetimer": "small",
      "bgcolor": true,
      "uppercase": false,
      "countries": null,
      "btnlinternal": null,
      "btnrinternal": null,
      "btnlmodal": null,
      "btnrmodal": null
    },
    carouselCards: {
      "title": "Our Destinations",
      "btnText": "Explore Destinations",
      "btnExternal": null,
      "description": "From turquoise beaches to timeless cities, our world-class partnerships open doors to dream destinations. Our current portfolio includes:",
      "bgColor": true,
      "decorativeLine": true,
      "autoscroll": null,
      "chevron": null,
      "imageaspec": 'aspec4-5',
      "cards": [
        {
          "id": 200,
          "title": "Italy: Rome, Venice, Florence, Milan, Sardinia & Puglia",
          "date": "2025-04-10",
          "tag": null,
          "description": "Step into the timeless elegance of Italy, where every city is a living museum. Our curated itineraries take you from the grandeur of Rome to the romantic canals of Venice, the Renaissance charm of Florence, the cosmopolitan energy of Milan, and the coastal escapes of Sardinia and Puglia. Through our exclusive partnerships with Baglioni Hotels and other luxury operators, PR Global delivers the Italy of your dreams—tailored, effortless, and unforgettable.",
          "urlExternal": null,
          "disclaimer": null,
          "btnltext": null,
          "btnrtext": null,
          "btnrexternal": null,
          "playvideo": false,
          "media": {
            "id": 848,
            "name": "BLOG Main - TPC.webp",
            "url": "https://thepalacecompany.com/BLOG_Main_TPC_7d0bfbf73a.webp",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/webp",
            "isUrlSigned": false
          },
          "urlinternal": null,
          "btnrinternal": null,
          "modal": null,
          "btnrmodal": null
        },
        {
          "id": 196,
          "title": "Maldives",
          "date": "2025-02-06",
          "tag": null,
          "description": "A sanctuary of barefoot luxury, the Maldives offers overwater villas, coral gardens, and sunsets that defy description. PR Global collaborates with premium hospitality providers in this exclusive destination to deliver once-in-a-lifetime escapes—perfect for honeymoons, proposals, or simply pressing pause on the outside world. Every detail, from seaplane transfers to private dinners on the beach, is arranged with precision and care.",
          "urlExternal": null,
          "disclaimer": null,
          "btnltext": null,
          "btnrtext": null,
          "btnrexternal": "gibran",
          "playvideo": false,
          "media": {
            "id": 835,
            "name": "The_Palace_Company_Gibran_Chapur_New_CEO.webp",
            "url": "https://www.thepalacecompany.com/The_Palace_Company_Gibran_Chapur_New_CEO_ec66af51ae.webp",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/webp",
            "isUrlSigned": false
          },
          "urlinternal": null,
          "btnrinternal": null,
          "modal": null,
          "btnrmodal": null
        },
        {
          "id": 197,
          "title": "Mexico: Cancún, Playa del Carmen, Cozumel & Los Cabos",
          "date": "2024-12-30",
          "tag": null,
          "description": "From the turquoise waters of the Caribbean to the dramatic cliffs of the Pacific, Mexico is the beating heart of PR Global. Our alliances with top hotel operators in Cancún, Playa del Carmen, Cozumel, and Los Cabos allow us to craft unforgettable journeys that blend luxury, cultural richness, and natural beauty. Whether it’s a romantic escape, family vacation, or wellness retreat, Mexico offers every kind of traveler a premium all-inclusive experience with world-class service.",
          "urlExternal": null,
          "disclaimer": null,
          "btnltext": null,
          "btnrtext": null,
          "btnrexternal": null,
          "playvideo": false,
          "media": {
            "id": 809,
            "name": "jose-chapur-cader-the-palace-company.webp",
            "url": "https://www.thepalacecompany.com/jose_chapur_cader_the_palace_company_cc7a3de70a.webp",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/webp",
            "isUrlSigned": false
          },
          "urlinternal": null,
          "btnrinternal": null,
          "modal": null,
          "btnrmodal": null
        },
        {
          "id": 138,
          "title": "Jamaica: Ocho Ríos (and soon Montego Bay)",
          "date": "2024-07-11",
          "tag": null,
          "description": "Feel the rhythm of the island in Ocho Ríos, where waterfalls meet reggae beats and relaxation becomes a lifestyle. PR Global offers seamless access to this tropical paradise through trusted hospitality partners. With upcoming expansion into Montego Bay, our presence in Jamaica is growing — bringing guests closer to the island’s lush landscapes, cultural legacy, and laid-back luxury.",
          "urlExternal": null,
          "disclaimer": null,
          "btnltext": null,
          "btnrtext": null,
          "btnrexternal": null,
          "playvideo": null,
          "media": {
            "id": 790,
            "name": "Content 3col article_900x540.webp",
            "url": "https://www.thepalacecompany.com/Content_3col_article_900x540_8c3ccf3bcc.webp",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/webp",
            "isUrlSigned": false
          },
          "urlinternal": null,
          "btnrinternal": null,
          "modal": null,
          "btnrmodal": null
        }
      ],
      "countries": null,
      "btninternal": null,
      "btnmodal": null
    },
    carouselCenter: {
      "title": "Coming Soon: Punta Cana, Turks and Caicos, Mykonos & More",
      "description": "PR Global is actively expanding its global footprint. We are currently finalizing partnerships in Punta Cana, Montego Bay, Turks and Caicos, Mykonos, and other high-demand destinations across Europe, the Caribbean, and Asia. As our network of hotel alliances grows, so does our ability to offer travelers unparalleled access to the world’s most beautiful places—always with our signature service and expertise.",
      "btnText": null,
      "btnExternal": null,
      "decorativeLine": true,
      "bgColor": true,
      "cards": [
        {
          "id": 97,
          "title": null,
          "btnText": null,
          "description": null,
          "urlExternal": null,
          "tag": null,
          "media": {
            "id": 699,
            "name": "beach-cleaning-environment-palace-foundation-the-palace-company.webp",
            "url": "https://www.thepalacecompany.com/beach_cleaning_environment_palace_foundation_the_palace_company_80e0e647f2.webp",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/webp",
            "isUrlSigned": false
          },
          "urlinternal": null,
          "modal": null
        },
        {
          "id": 98,
          "title": null,
          "btnText": null,
          "description": null,
          "urlExternal": null,
          "tag": null,
          "media": {
            "id": 698,
            "name": "members-residence-palace-elite-the-palace-company.webp",
            "url": "https://www.thepalacecompany.com/members_residence_palace_elite_the_palace_company_537eb3c7eb.webp",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/webp",
            "isUrlSigned": false
          },
          "urlinternal": null,
          "modal": null
        },
        {
          "id": 99,
          "title": null,
          "btnText": null,
          "description": null,
          "urlExternal": null,
          "tag": null,
          "media": {
            "id": 660,
            "name": "lily_1_af6e7d8eb8_Content-center_3600x1543.webp",
            "url": "https://www.thepalacecompany.com/lily_1_af6e7d8eb8_Content_center_3600x1543_59e47ca4ba.webp",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/webp",
            "isUrlSigned": false
          },
          "urlinternal": null,
          "modal": null
        },
        {
          "id": 100,
          "title": null,
          "btnText": null,
          "description": null,
          "urlExternal": null,
          "tag": null,
          "media": {
            "id": 849,
            "name": "Vlad01 2.png",
            "url": "https://thepalacecompany.com/Vlad01_2_8d772238da.png",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/png",
            "isUrlSigned": false
          },
          "urlinternal": null,
          "modal": null
        },
        {
          "id": 101,
          "title": null,
          "btnText": null,
          "description": null,
          "urlExternal": null,
          "tag": null,
          "media": {
            "id": 867,
            "name": "apertura-the-grand-punta-cana.webp",
            "url": "https://thepalacecompany.com/apertura_the_grand_punta_cana_57845d6a9d.webp",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/webp",
            "isUrlSigned": false
          },
          "urlinternal": null,
          "modal": null
        },
        {
          "id": 102,
          "title": null,
          "btnText": null,
          "description": null,
          "urlExternal": null,
          "tag": null,
          "media": {
            "id": 791,
            "name": "Content Center_ 3600x1543.webp",
            "url": "https://www.thepalacecompany.com/Content_Center_3600x1543_d6dd100f55.webp",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/webp",
            "isUrlSigned": false
          },
          "urlinternal": null,
          "modal": null
        }
      ],
      "countries": null,
      "btninternal": null,
      "btnmodal": null
    },
  },
  es: {
    hero: {
      "size": "max",
      "ab_testing": null,
      "uppercase": false,
      "transitiontime": null,
      "overlay": "partial",
      "soundonscroll": false,
      "cards": [
        {
          "id": 128,
          "title": "PREMIER ELEGANCE ACROSS THE GLOBE ",
          "description": null,
          "timerText": null,
          "timerDateTime": null,
          "startDate": null,
          "endDate": null,
          "btnExternal": null,
          "timecard": null,
          "idcard": null,
          "media": {
            "id": 728,
            "name": "index.png",
            "url": "assets/img/heroes/index.png",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/png",
            "isUrlSigned": false
          },
          "mediam": null,
          "btninternal": null,
          "btnmodal": null
        }
      ],
      "countries": null
    },
    carouselBadges: {
      "title": "We Are PR Global Es",
      "description": "A full-service tour operator redefining how the world travels.",
      "decorativeLine": true,
      "htag": "h1",
      "btnText": "Learn More",
      "cards": [
        {
          "id": 3,
          "urlexternal": "https://www.moonpalace.com",
          "media": {
            "id": 599,
            "name": "Moon Palace.png",
            "url": "assets/img/caousel-badges/Moon_Palace_ff32ef74b8.png",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/png",
            "isUrlSigned": false
          }
        },
        {
          "id": 4,
          "urlexternal": "https://www.palaceresorts.com",
          "media": {
            "id": 594,
            "name": "Palace_Resorts_Blue.png",
            "url": "assets/img/caousel-badges/Palace_Resorts_Blue_605ef2b293.png",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/png",
            "isUrlSigned": false
          }
        },
        {
          "id": 13,
          "urlexternal": "https://www.leblancsparesorts.com",
          "media": {
            "id": 798,
            "name": "lbb_hotels_resorts_black_footer.svg",
            "url": "assets/img/caousel-badges/lbb_hotels_resorts_black_footer_bb4d70a02d.svg",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/svg+xml",
            "isUrlSigned": false
          }
        },
        {
          "id": 14,
          "urlexternal": "https://www.baglionihotels.com",
          "media": {
            "id": 741,
            "name": "baglioni-logo.svg",
            "url": "assets/img/caousel-badges/baglioni_logo_94c83cc23e.svg",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/svg+xml",
            "isUrlSigned": false
          }
        },
        {
          "id": 5,
          "urlexternal": "https://www.palaceelite.com",
          "media": {
            "id": 738,
            "name": "palace-elite.svg",
            "url": "assets/img/caousel-badges/palace_elite_05e7c6f3c6.svg",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/svg+xml",
            "isUrlSigned": false
          }
        }
      ],
      "countries": null
    },
    contentGroup: {
      "stylecomponent": "Colum",
      "component": "ContentGroup",
      "enablebg": false,
      "countries": null,
      "cards": [
        {
          "id": 128,
          "title": "Itinerary creation",
          "tag": null,
          "description": "We design complete travel experiences that integrate flights, accommodation, local transfers, tours, entertainment, and cultural immersion.",
          "disclaimer": null,
          "bookto": null,
          "bookfrom": null,
          "textbook": null,
          "bookstart": null,
          "stayto": null,
          "stayfrom": null,
          "textstay": null,
          "staystart": null,
          "btnltext": null,
          "btnlexternal": null,
          "btnrtext": null,
          "btnrexternal": null,
          "decorativeline": true,
          "playvideo": true,
          "startdate": null,
          "enddate": null,
          "textbookto": null,
          "textstayto": null,
          "enableicon": false,
          "align": "left",
          "media": {
            "id": 2394,
            "name": "los-cabos-travel-destination-le-blanc-spa-resorts.webp",
            "alternativeText": null,
            "caption": null,
            "width": 768,
            "height": 650,
            "imageformats": null,
            "hash": "los_cabos_travel_destination_le_blanc_spa_resorts_c54af9ab23",
            "ext": ".webp",
            "mime": "image/webp",
            "size": 41.91,
            "url": "https://www.leblancsparesorts.com/los_cabos_travel_destination_le_blanc_spa_resorts_c54af9ab23.webp",
            "previewUrl": null,
            "provider": "aws-s3",
            "provider_metadata": null,
            "isUrlSigned": true
          },
          "btnrinternal": null,
          "btnrmodal": null,
          "btnlinternal": null,
          "btnlmodal": null
        },
        {
          "id": 129,
          "title": "Direct Negotiations",
          "tag": null,
          "description": "We partner with top-tier hotels, airlines, restaurants, and experience providers to offer exclusive pricing and access you won’t find on consumer platforms.",
          "disclaimer": null,
          "bookto": null,
          "bookfrom": null,
          "textbook": null,
          "bookstart": null,
          "stayto": null,
          "stayfrom": null,
          "textstay": null,
          "staystart": null,
          "btnltext": null,
          "btnlexternal": null,
          "btnrtext": null,
          "btnrexternal": null,
          "decorativeline": true,
          "playvideo": true,
          "startdate": null,
          "enddate": null,
          "textbookto": null,
          "textstayto": null,
          "enableicon": false,
          "align": "left",
          "media": {
            "id": 1955,
            "name": "ancestral-massage-spa-le-blanc-spa-resorts.webp",
            "alternativeText": "Healing touch Spa",
            "caption": "Achieve a complete state of wellbeing",
            "width": 1620,
            "height": 1080,
            "imageformats": null,
            "hash": "ancestral-massage-spa-le-blanc-spa-resorts_cd9c0112ba",
            "ext": ".webp",
            "mime": "image/webp",
            "size": 105.74,
            "url": "https://www.leblancsparesorts.com/ancestral-massage-spa-le-blanc-spa-resorts_cd9c0112ba.webp",
            "previewUrl": null,
            "provider": "aws-s3",
            "provider_metadata": null,
            "isUrlSigned": true
          },
          "btnrinternal": null,
          "btnrmodal": null,
          "btnlinternal": null,
          "btnlmodal": null
        },
        {
          "id": 130,
          "title": "End-to-end coordination",
          "tag": null,
          "description": "We handle every detail — so our travelers can focus on enjoying, not planning.",
          "disclaimer": null,
          "bookto": null,
          "bookfrom": null,
          "textbook": null,
          "bookstart": null,
          "stayto": null,
          "stayfrom": null,
          "textstay": null,
          "staystart": null,
          "btnltext": null,
          "btnlexternal": null,
          "btnrtext": null,
          "btnrexternal": null,
          "decorativeline": true,
          "playvideo": true,
          "startdate": null,
          "enddate": null,
          "textbookto": null,
          "textstayto": null,
          "enableicon": false,
          "align": "left",
          "media": {
            "id": 2394,
            "name": "los-cabos-travel-destination-le-blanc-spa-resorts.webp",
            "alternativeText": null,
            "caption": null,
            "width": 768,
            "height": 650,
            "imageformats": null,
            "hash": "los_cabos_travel_destination_le_blanc_spa_resorts_c54af9ab23",
            "ext": ".webp",
            "mime": "image/webp",
            "size": 41.91,
            "url": "https://www.leblancsparesorts.com/los_cabos_travel_destination_le_blanc_spa_resorts_c54af9ab23.webp",
            "previewUrl": null,
            "provider": "aws-s3",
            "provider_metadata": null,
            "isUrlSigned": true
          },
          "btnrinternal": null,
          "btnrmodal": null,
          "btnlinternal": null,
          "btnlmodal": null
        }
      ]
    },
    contentGroup2: {
      "stylecomponent": "Colum",
      "component": "ContentGroup",
      "enablebg": false,
      "countries": null,
      "cards": [
        {
          "id": 128,
          "title": "On-trip support",
          "tag": null,
          "description": "Our guests have on-the-ground assistance before, during, and after their trip — peace of mind guaranteed.",
          "disclaimer": null,
          "bookto": null,
          "bookfrom": null,
          "textbook": null,
          "bookstart": null,
          "stayto": null,
          "stayfrom": null,
          "textstay": null,
          "staystart": null,
          "btnltext": null,
          "btnlexternal": null,
          "btnrtext": null,
          "btnrexternal": null,
          "decorativeline": true,
          "playvideo": true,
          "startdate": null,
          "enddate": null,
          "textbookto": null,
          "textstayto": null,
          "enableicon": false,
          "align": "left",
          "media": {
            "id": 2394,
            "name": "los-cabos-travel-destination-le-blanc-spa-resorts.webp",
            "alternativeText": null,
            "caption": null,
            "width": 768,
            "height": 650,
            "imageformats": null,
            "hash": "los_cabos_travel_destination_le_blanc_spa_resorts_c54af9ab23",
            "ext": ".webp",
            "mime": "image/webp",
            "size": 41.91,
            "url": "https://www.leblancsparesorts.com/los_cabos_travel_destination_le_blanc_spa_resorts_c54af9ab23.webp",
            "previewUrl": null,
            "provider": "aws-s3",
            "provider_metadata": null,
            "isUrlSigned": true
          },
          "btnrinternal": null,
          "btnrmodal": null,
          "btnlinternal": null,
          "btnlmodal": null
        },
        {
          "id": 129,
          "title": "Flexible to your budget",
          "tag": null,
          "description": "From ultra-luxury to value-based packages, we scale experiences to fit your needs — without sacrificing service quality.",
          "disclaimer": null,
          "bookto": null,
          "bookfrom": null,
          "textbook": null,
          "bookstart": null,
          "stayto": null,
          "stayfrom": null,
          "textstay": null,
          "staystart": null,
          "btnltext": null,
          "btnlexternal": null,
          "btnrtext": null,
          "btnrexternal": null,
          "decorativeline": true,
          "playvideo": true,
          "startdate": null,
          "enddate": null,
          "textbookto": null,
          "textstayto": null,
          "enableicon": false,
          "align": "left",
          "media": {
            "id": 1955,
            "name": "ancestral-massage-spa-le-blanc-spa-resorts.webp",
            "alternativeText": "Healing touch Spa",
            "caption": "Achieve a complete state of wellbeing",
            "width": 1620,
            "height": 1080,
            "imageformats": null,
            "hash": "ancestral-massage-spa-le-blanc-spa-resorts_cd9c0112ba",
            "ext": ".webp",
            "mime": "image/webp",
            "size": 105.74,
            "url": "https://www.leblancsparesorts.com/ancestral-massage-spa-le-blanc-spa-resorts_cd9c0112ba.webp",
            "previewUrl": null,
            "provider": "aws-s3",
            "provider_metadata": null,
            "isUrlSigned": true
          },
          "btnrinternal": null,
          "btnrmodal": null,
          "btnlinternal": null,
          "btnlmodal": null
        },
        {
          "id": 130,
          "title": "Global market intelligence",
          "tag": null,
          "description": "We continually research travel trends and destination demand to build packages aligned with traveler desires and high-value markets.",
          "disclaimer": null,
          "bookto": null,
          "bookfrom": null,
          "textbook": null,
          "bookstart": null,
          "stayto": null,
          "stayfrom": null,
          "textstay": null,
          "staystart": null,
          "btnltext": null,
          "btnlexternal": null,
          "btnrtext": null,
          "btnrexternal": null,
          "decorativeline": true,
          "playvideo": true,
          "startdate": null,
          "enddate": null,
          "textbookto": null,
          "textstayto": null,
          "enableicon": false,
          "align": "left",
          "media": {
            "id": 2394,
            "name": "los-cabos-travel-destination-le-blanc-spa-resorts.webp",
            "alternativeText": null,
            "caption": null,
            "width": 768,
            "height": 650,
            "imageformats": null,
            "hash": "los_cabos_travel_destination_le_blanc_spa_resorts_c54af9ab23",
            "ext": ".webp",
            "mime": "image/webp",
            "size": 41.91,
            "url": "https://www.leblancsparesorts.com/los_cabos_travel_destination_le_blanc_spa_resorts_c54af9ab23.webp",
            "previewUrl": null,
            "provider": "aws-s3",
            "provider_metadata": null,
            "isUrlSigned": true
          },
          "btnrinternal": null,
          "btnrmodal": null,
          "btnlinternal": null,
          "btnlmodal": null
        }
      ]
    },
    contentAlign: {
      "layout": "align",
      "title": "Fully Personalized Travel Experiences",
      "description": "Powered by strategic alliances with world-class hotel operators, we offer more than just bookings — we orchestrate complete journeys, including:",
      "list": "Flights\nTransfers\nAccommodations\nActivities\nCar Rental",
      "align": "left",
      "tag": null,
      "iconlist": "bullet",
      "viewmore": "Ver mas",
      "viewless": "Ver menos",
      "stayfrom": null,
      "stayto": null,
      "btnltext": '',
      "btnlexternal": null,
      "btnrtext": '',
      "btnrexternal": null,
      "startdate": null,
      "enddate": null,
      "bookfrom": null,
      "bookto": null,
      "decorativeline": true,
      "textbook": null,
      "bookstart": null,
      "textstay": null,
      "staystart": null,
      "disclaimer": null,
      "ab_testing": null,
      "largedescription": null,
      "showmodal": null,
      "titlemodal": null,
      "disableviewmore": false,
      "textbookto": null,
      "textstayto": null,
      "countries": null,
      "media": {
        "id": 580,
        "name": "environment-palace-foundation-the-palace-company.webp",
        "url": "assets/img/content-align/environment-palace-foundation-the-palace-company.webp",
        "caption": null,
        "alternativeText": null,
        "imageformats": null,
        "mime": "image/webp",
        "isUrlSigned": false
      },
      "btnlinternal": null,
      "btnrinternal": null,
      "btnlmodal": null,
      "btnrmodal": null
    },
    contentIntro: {
      "title": "What We Do",
      "description": "We create journeys. Not transactions.\n\nAs a tour operator, PR Global goes beyond reservations to build immersive, end-to-end travel packages with unmatched coordination and personalization.",
      "decorativeLine": true,
      "tagH": "h2",
      "btnltext": null,
      "btnlexternal": null,
      "btnrtext": null,
      "btnrexternal": null,
      "removepaddingbottom": false,
      "ab_testing": null,
      "timerdatetime": null,
      "timertext": null,
      "themetimer": "default",
      "sizetimer": "small",
      "bgcolor": true,
      "uppercase": false,
      "countries": null,
      "btnlinternal": null,
      "btnrinternal": null,
      "btnlmodal": null,
      "btnrmodal": null
    },
    carouselCards: {
      "title": "Our Destinations",
      "btnText": "Explore Destinations",
      "btnExternal": null,
      "description": "From turquoise beaches to timeless cities, our world-class partnerships open doors to dream destinations. Our current portfolio includes:",
      "bgColor": true,
      "decorativeLine": true,
      "autoscroll": null,
      "chevron": null,
      "imageaspec": 'aspec4-5',
      "cards": [
        {
          "id": 200,
          "title": "Italy: Rome, Venice, Florence, Milan, Sardinia & Puglia",
          "date": "2025-04-10",
          "tag": null,
          "description": "Step into the timeless elegance of Italy, where every city is a living museum. Our curated itineraries take you from the grandeur of Rome to the romantic canals of Venice, the Renaissance charm of Florence, the cosmopolitan energy of Milan, and the coastal escapes of Sardinia and Puglia. Through our exclusive partnerships with Baglioni Hotels and other luxury operators, PR Global delivers the Italy of your dreams—tailored, effortless, and unforgettable.",
          "urlExternal": null,
          "disclaimer": null,
          "btnltext": null,
          "btnrtext": null,
          "btnrexternal": null,
          "playvideo": false,
          "media": {
            "id": 848,
            "name": "BLOG Main - TPC.webp",
            "url": "https://thepalacecompany.com/BLOG_Main_TPC_7d0bfbf73a.webp",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/webp",
            "isUrlSigned": false
          },
          "urlinternal": null,
          "btnrinternal": null,
          "modal": null,
          "btnrmodal": null
        },
        {
          "id": 196,
          "title": "Maldives",
          "date": "2025-02-06",
          "tag": null,
          "description": "A sanctuary of barefoot luxury, the Maldives offers overwater villas, coral gardens, and sunsets that defy description. PR Global collaborates with premium hospitality providers in this exclusive destination to deliver once-in-a-lifetime escapes—perfect for honeymoons, proposals, or simply pressing pause on the outside world. Every detail, from seaplane transfers to private dinners on the beach, is arranged with precision and care.",
          "urlExternal": null,
          "disclaimer": null,
          "btnltext": null,
          "btnrtext": null,
          "btnrexternal": "gibran",
          "playvideo": false,
          "media": {
            "id": 835,
            "name": "The_Palace_Company_Gibran_Chapur_New_CEO.webp",
            "url": "https://www.thepalacecompany.com/The_Palace_Company_Gibran_Chapur_New_CEO_ec66af51ae.webp",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/webp",
            "isUrlSigned": false
          },
          "urlinternal": null,
          "btnrinternal": null,
          "modal": null,
          "btnrmodal": null
        },
        {
          "id": 197,
          "title": "Mexico: Cancún, Playa del Carmen, Cozumel & Los Cabos",
          "date": "2024-12-30",
          "tag": null,
          "description": "From the turquoise waters of the Caribbean to the dramatic cliffs of the Pacific, Mexico is the beating heart of PR Global. Our alliances with top hotel operators in Cancún, Playa del Carmen, Cozumel, and Los Cabos allow us to craft unforgettable journeys that blend luxury, cultural richness, and natural beauty. Whether it’s a romantic escape, family vacation, or wellness retreat, Mexico offers every kind of traveler a premium all-inclusive experience with world-class service.",
          "urlExternal": null,
          "disclaimer": null,
          "btnltext": null,
          "btnrtext": null,
          "btnrexternal": null,
          "playvideo": false,
          "media": {
            "id": 809,
            "name": "jose-chapur-cader-the-palace-company.webp",
            "url": "https://www.thepalacecompany.com/jose_chapur_cader_the_palace_company_cc7a3de70a.webp",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/webp",
            "isUrlSigned": false
          },
          "urlinternal": null,
          "btnrinternal": null,
          "modal": null,
          "btnrmodal": null
        },
        {
          "id": 138,
          "title": "Jamaica: Ocho Ríos (and soon Montego Bay)",
          "date": "2024-07-11",
          "tag": null,
          "description": "Feel the rhythm of the island in Ocho Ríos, where waterfalls meet reggae beats and relaxation becomes a lifestyle. PR Global offers seamless access to this tropical paradise through trusted hospitality partners. With upcoming expansion into Montego Bay, our presence in Jamaica is growing — bringing guests closer to the island’s lush landscapes, cultural legacy, and laid-back luxury.",
          "urlExternal": null,
          "disclaimer": null,
          "btnltext": null,
          "btnrtext": null,
          "btnrexternal": null,
          "playvideo": null,
          "media": {
            "id": 790,
            "name": "Content 3col article_900x540.webp",
            "url": "https://www.thepalacecompany.com/Content_3col_article_900x540_8c3ccf3bcc.webp",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/webp",
            "isUrlSigned": false
          },
          "urlinternal": null,
          "btnrinternal": null,
          "modal": null,
          "btnrmodal": null
        }
      ],
      "countries": null,
      "btninternal": null,
      "btnmodal": null
    },
    carouselCenter: {
      "title": "Coming Soon: Punta Cana, Turks and Caicos, Mykonos & More",
      "description": "PR Global is actively expanding its global footprint. We are currently finalizing partnerships in Punta Cana, Montego Bay, Turks and Caicos, Mykonos, and other high-demand destinations across Europe, the Caribbean, and Asia. As our network of hotel alliances grows, so does our ability to offer travelers unparalleled access to the world’s most beautiful places—always with our signature service and expertise.",
      "btnText": null,
      "btnExternal": null,
      "decorativeLine": true,
      "bgColor": true,
      "cards": [
        {
          "id": 97,
          "title": null,
          "btnText": null,
          "description": null,
          "urlExternal": null,
          "tag": null,
          "media": {
            "id": 699,
            "name": "beach-cleaning-environment-palace-foundation-the-palace-company.webp",
            "url": "https://www.thepalacecompany.com/beach_cleaning_environment_palace_foundation_the_palace_company_80e0e647f2.webp",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/webp",
            "isUrlSigned": false
          },
          "urlinternal": null,
          "modal": null
        },
        {
          "id": 98,
          "title": null,
          "btnText": null,
          "description": null,
          "urlExternal": null,
          "tag": null,
          "media": {
            "id": 698,
            "name": "members-residence-palace-elite-the-palace-company.webp",
            "url": "https://www.thepalacecompany.com/members_residence_palace_elite_the_palace_company_537eb3c7eb.webp",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/webp",
            "isUrlSigned": false
          },
          "urlinternal": null,
          "modal": null
        },
        {
          "id": 99,
          "title": null,
          "btnText": null,
          "description": null,
          "urlExternal": null,
          "tag": null,
          "media": {
            "id": 660,
            "name": "lily_1_af6e7d8eb8_Content-center_3600x1543.webp",
            "url": "https://www.thepalacecompany.com/lily_1_af6e7d8eb8_Content_center_3600x1543_59e47ca4ba.webp",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/webp",
            "isUrlSigned": false
          },
          "urlinternal": null,
          "modal": null
        },
        {
          "id": 100,
          "title": null,
          "btnText": null,
          "description": null,
          "urlExternal": null,
          "tag": null,
          "media": {
            "id": 849,
            "name": "Vlad01 2.png",
            "url": "https://thepalacecompany.com/Vlad01_2_8d772238da.png",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/png",
            "isUrlSigned": false
          },
          "urlinternal": null,
          "modal": null
        },
        {
          "id": 101,
          "title": null,
          "btnText": null,
          "description": null,
          "urlExternal": null,
          "tag": null,
          "media": {
            "id": 867,
            "name": "apertura-the-grand-punta-cana.webp",
            "url": "https://thepalacecompany.com/apertura_the_grand_punta_cana_57845d6a9d.webp",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/webp",
            "isUrlSigned": false
          },
          "urlinternal": null,
          "modal": null
        },
        {
          "id": 102,
          "title": null,
          "btnText": null,
          "description": null,
          "urlExternal": null,
          "tag": null,
          "media": {
            "id": 791,
            "name": "Content Center_ 3600x1543.webp",
            "url": "https://www.thepalacecompany.com/Content_Center_3600x1543_d6dd100f55.webp",
            "caption": null,
            "alternativeText": null,
            "imageformats": null,
            "mime": "image/webp",
            "isUrlSigned": false
          },
          "urlinternal": null,
          "modal": null
        }
      ],
      "countries": null,
      "btninternal": null,
      "btnmodal": null
    },
  },
}
</script>

<template>
  <div>
    <hero v-bind="data[locale].hero" />
    <carousel-badges v-bind="data[locale].carouselBadges" />
    <content-intro v-bind="data[locale].contentIntro" />
    <content-group v-bind="data[locale].contentGroup" />
    <content-group v-bind="data[locale].contentGroup2" />    
    <content-align v-bind="data[locale].contentAlign" />
    
    <carousel-cards v-bind="data[locale].carouselCards" />
    <carousel-center v-bind="data[locale].carouselCenter" />
  </div>
</template>
